
[general]
base_dir = "/path/to/your/base/directory/"
output_dir = "/path/to/your/output/directory/"
log_dir = "/path/to/your/log/directory/"
vae_participant_id = "RCS04"
resnet_output_dir = "/path/to/your/resnet/output/directory/"
val_output_dir = "/path/to/your/validation/output/directory/"
participants = ["RCS02", "RCS04", "RCS05", "RCS06", "RCS07"]
val_data_folder = "/path/to/your/validation/data/folder/{}/during_pre_stim_fornoisepaper/fif/"
vae_autocorr_files_config = "/path/to/your/vae_autocorr_files_config.toml"

[data]
duration = 2.5
channels = 86
num_trials = 3000
val_num_trials = 1000
sampling_rate = 1000

[vae]
latent_factors = 50
kernel_len = 15
pad_len = 3
stride_len = 1
n_epochs = 50
batch_size = 5
learning_rate = 0.0001
patience = 5

[resnet]
image_size = 672
learning_rate = 0.0001
batch_size = 8
num_epochs = 20

[noise]
amplitudes = [4, 6, 10, 14]

[fnames]
ieeg_for_vae_fnames = "/path/to/your/ieeg_for_vae_fnames.toml"

[model]
noise_threshold = 0.2
n_permutations = 1000
image_size = 672
